'use strict';

function toStructurizr(view, opts = {}) {
  const overview = (view.diagrams && view.diagrams.overview) || { nodes: [], edges: [] };
  const dynamic = view.kind === 'focused'
    ? (((view.diagrams && view.diagrams.runtime && view.diagrams.runtime.edges.length > 0) && view.diagrams.runtime) ||
       ((view.diagrams && view.diagrams.endToEnd) || null))
    : null;
  const systemName = escapeDsl(opts.systemName || 'Legacy System');
  const workspaceName = escapeDsl(view.title || 'Executive View');
  const softwareSystemId = 'legacy';
  const nodeIds = new Map();
  const nodes = uniqueNodes([
    ...(overview.nodes || []),
    ...((dynamic && dynamic.nodes) || []),
  ]);
  const lines = [
    `workspace "${workspaceName}" "Generated by UAI executive command" {`,
    '  !identifiers hierarchical',
    '',
    '  model {',
    `    ${softwareSystemId} = softwareSystem "${systemName}" "Generated from UAI model" {`,
  ];

  const renderedNodes = nodes.length > 0
    ? nodes
    : [{ id: 'summary:empty', label: 'No Data', type: 'summary', description: 'No executive view data was available.' }];

  for (const node of renderedNodes) {
    const id = dslId(node.id, nodeIds);
    lines.push(
      `      ${id} = container "${escapeDsl(node.label)}" "${escapeDsl(node.description || defaultDescription(node.type))}" "${escapeDsl(technologyFor(node.type))}"`,
    );
  }

  lines.push('    }', '');

  for (const edge of overview.edges || []) {
    const fromId = nodeIds.get(edge.from);
    const toId = nodeIds.get(edge.to);
    if (!fromId || !toId) {
      continue;
    }
    lines.push(`    ${softwareSystemId}.${fromId} -> ${softwareSystemId}.${toId} "${escapeDsl(edge.label || edge.kind || 'Uses')}"`);
  }

  lines.push('  }', '', '  views {');
  lines.push(`    container ${softwareSystemId} "${view.slug || 'executive_view'}" {`);
  lines.push('      include *');
  lines.push(`      autolayout ${overview.direction === 'TD' ? 'tb' : 'lr'}`);
  lines.push('    }', '');

  if (dynamic && dynamic.edges && dynamic.edges.length > 0) {
    lines.push(`    dynamic ${softwareSystemId} "${view.slug || 'focused_view'}_dynamic" {`);
    for (const edge of dynamic.edges) {
      const fromId = nodeIds.get(edge.from);
      const toId = nodeIds.get(edge.to);
      if (!fromId || !toId) {
        continue;
      }
      lines.push(`      ${softwareSystemId}.${fromId} -> ${softwareSystemId}.${toId} "${escapeDsl(edge.label || edge.kind || 'Flows')}"`);
    }
    lines.push(`      autolayout ${dynamic.direction === 'TD' ? 'tb' : 'lr'}`);
    lines.push('    }', '');
  }

  lines.push('    theme default');
  lines.push('  }');
  lines.push('}');

  return lines.join('\n');
}

function dslId(raw, registry) {
  const sanitized = String(raw || 'node')
    .replace(/[^A-Za-z0-9_]/g, '_')
    .replace(/^_+/, '')
    .replace(/_+/g, '_') || 'node';
  let candidate = sanitized;
  let idx = 1;
  while ([...registry.values()].includes(candidate)) {
    candidate = `${sanitized}_${idx++}`;
  }
  registry.set(raw, candidate);
  return candidate;
}

function defaultDescription(type) {
  switch (type) {
    case 'job': return 'Batch entrypoint';
    case 'step': return 'Batch runtime step';
    case 'program': return 'COBOL program';
    case 'procedure': return 'Database procedure';
    case 'table': return 'Persistent table';
    case 'dataset': return 'Batch dataset';
    case 'screen': return 'Screen entrypoint';
    case 'class': return 'Application class';
    case 'component': return 'Runtime component';
    case 'summary': return 'Collapsed node summary';
    default: return 'Legacy artifact';
  }
}

function technologyFor(type) {
  switch (type) {
    case 'job': return 'JCL';
    case 'step': return 'JCL Step';
    case 'program': return 'COBOL';
    case 'procedure': return 'SQL / DB2';
    case 'table': return 'DB2 Table';
    case 'dataset': return 'Dataset';
    case 'screen': return 'VB6';
    case 'class': return 'VB6 Class';
    case 'component': return 'Component';
    case 'summary': return 'Summary';
    default: return 'Legacy';
  }
}

function escapeDsl(value) {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, ' ');
}

function uniqueNodes(nodes) {
  const byId = new Map();
  for (const node of nodes || []) {
    if (!node || !node.id) {
      continue;
    }
    if (!byId.has(node.id)) {
      byId.set(node.id, node);
    }
  }
  return [...byId.values()];
}

module.exports = {
  toStructurizr,
};
